#' Univariate Conditional Average Treatment Effect Estimation
#'
#' \code{unicate()} performs inference about \code{biomarkers}' capacity to
#'   modify treatment effects in randomized control trials with continuous or
#'   binary outcomes. The strength of each \code{biomarkers}' treatment effect
#'   modification is captured by an unknown variable importance parameter
#'   defined as the slope of the marginal conditional average treatment effect's
#'   linear approximation. In all but pathological cases, the larger the
#'   absolute value of this parameter, the greater the treatment effect
#'   modification. \code{unicate()} implements assumption-lean, cross-validated
#'   inference procedures about these variable importance parameters based on
#'   semiparametric theory. Assuming that the \code{biomarkers} have non-zero
#'   variance, estimates are generated by an unbiased and consistent estimator.
#'   Tests assessing whether these slope parameters are significantly different
#'   from zero are also performed; they are valid under the same
#'   bounded-variance condition.
#'
#' @param data A \code{data.frame} or \code{tibble} object containing the
#'   outcome variable, treatment indicator, and pre-treatment covariates. Note
#'   that the biomarkers are considered be a subset of the covariates.
#' @param outcome A \code{character} defining the name of the outcome variable
#'   in \code{data}. The outcome must be a continuous or a binary factor
#'   variable.
#' @param treatment A \code{character} indicating the name of the binary
#'   treatment variable in \code{data}.
#' @param covariates A \code{character} vector listing the pre-treatment
#'   covariates variables in \code{data}.
#' @param biomarkers A \code{character} vector listing the pre-treatment
#'   biomarkers variables in \code{data}. \code{biomarkers} must be a subset of
#'   \code{covariates}.
#' @param super_learner A \code{\link[sl3:Lrnr_sl]{Lrnr_sl}} object. If set
#'   to \code{NULL}, a default SuperLearner is used. If the outcome variable is
#'   continuous, the default's library of base learners is made up of a
#'   linear model, penalized linear models (LASSO and elasticnet), a spline
#'   regression, XGBoost, a Random Forest, and the mean model. When the outcome
#'   variable is binary, the base learner library consists of (penalized)
#'   logistic regression models, XGBoost, a Random Forests, and the mean model.
#'   The type of outcome is automatically detected.
#' @param propensity_score_ls A named \code{numeric} \code{list} providing the
#'   propensity scores for the treatment conditions. The first element of the
#'   list should correspond to the "treatment" condition, and the second to the
#'   "control" condition, whatever their names may be.
#' @param v_folds A \code{numeric} indicating the number of folds used for
#'   V-fold cross-validation. Defaults to \code{5}.
#' @param parallel A \code{logical} determining whether to use
#'   \code{\link[origami:cross_validate]{origami}}'s built-in parallelized
#'   cross-validation routines. This parallelization framework is built upon
#'   the \href{https://cran.r-project.org/package=future}{\code{future}} suite.
#'   Defaults to \code{FALSE}.
#'
#' @return A \code{tibble} with rows corresponding to the specified
#'   \code{biomarkers}. Each row contains an estimate of the
#'   treatment-modification variable importance parameter, its standard error,
#'   and the nominal and adjusted p-values of the accompanying test. FDR and
#'   FWER adjustments are performed using the \code{\link[stats]{p.adjust}}
#'   function with the \code{method} argument set to \code{"BH"} and
#'   \code{"holm"}, respectively. The \code{biomarkers} are ordered by
#'   significance.
#'
#' @export
unicate <- function(
  data,
  outcome,
  treatment,
  covariates,
  biomarkers,
  super_learner = NULL,
  propensity_score_ls,
  v_folds = 5L,
  parallel = FALSE
) {

  # assess the data quality and formatting, and prepare it for analysis
  data <- prep_data(data, outcome, treatment, covariates, biomarkers)

  # compute CV coefficients and CV influence curves
  cv_ls <- estimate_univariate_cates(
    data, outcome, treatment, biomarkers, super_learner, propensity_score_ls,
    v_folds, parallel
  )

  # compute the table of biomarker coefficients and standard errors
  biomarkers_tbl <- compute_coefs_tbl(cv_ls)

  # perform tests using the estimated coefficients and standard errors
  biomarkers_tbl <- perform_inference(biomarkers_tbl)

  return(biomarkers_tbl)
}
